alter session set "_ORACLE_SCRIPT"=true;

CREATE USER ckan IDENTIFIED BY ckan;

GRANT CONNECT TO ckan;
GRANT CONNECT, RESOURCE, DBA TO ckan;
GRANT CREATE SESSION TO ckan;
GRANT ALL PRIVILEGE TO ckan;
GRANT UNLIMITED TABLESPACE TO ckan;

CREATE TABLE ckan.test_table(
	id NUMBER GENERATED by default on null as IDENTITY PRIMARY KEY,
	description VARCHAR(200) NOT NULL
);

INSERT INTO ckan.test_table(description) VALUES ('oracle_desc1');
INSERT INTO ckan.test_table(description) VALUES ('oracle_desc2');
INSERT INTO ckan.test_table(description) VALUES ('oracle_desc3');
INSERT INTO ckan.test_table(description) VALUES ('oracle_desc4');
INSERT INTO ckan.test_table(description) VALUES ('oracle_desc5');
INSERT INTO ckan.test_table(description) VALUES ('oracle_desc6');

